### ISSUE TITLE
I do nothing and this error happens, bot shutsdown after

### ISSUE THREAD

**Issue by LightslicerGP** [Faf4a/aoi.sqlite#1]
```javascript
c:\Users\LightslicerGP\node_modules\aoi.sqlite\classes\Database.js:210
      this.client.db.prepare(sql).run(query);
                                  ^

TypeError: SQLite3 can only bind numbers, strings, bigints, buffers, and null
    at c:\Users\LightslicerGP\node_modules\aoi.sqlite\classes\Database.js:210:35
    at sqliteTransaction (c:\Users\LightslicerGP\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
    at SQLDatabase.deleteMany (c:\Users\LightslicerGP\node_modules\aoi.sqlite\classes\Database.js:214:7)
    at handleResidueData (c:\Users\LightslicerGP\node_modules\aoi.js\src\events\Custom\handleResidueData.js:2:21)
    at Timeout._onTimeout (c:\Users\LightslicerGP\node_modules\aoi.sqlite\classes\Database.js:79:73)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```
no idea, here and there the bot just gives an error like this and then it breaks. i have no clue

**Comment by LightslicerGP** [comment]
```javascript
c:\Users\LightslicerGP\node_modules\aoi.sqlite\classes\Database.js:210
      this.client.db.prepare(sql).run(query);
                                  ^

TypeError: SQLite3 can only bind numbers, strings, bigints, buffers, and null
    at c:\Users\LightslicerGP\node_modules\aoi.sqlite\classes\Database.js:210:35
    at sqliteTransaction (c:\Users\LightslicerGP\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
    at SQLDatabase.deleteMany (c:\Users\LightslicerGP\node_modules\aoi.sqlite\classes\Database.js:214:7)
    at handleResidueData (c:\Users\LightslicerGP\node_modules\aoi.js\src\events\Custom\handleResidueData.js:2:21)
    at Timeout._onTimeout (c:\Users\LightslicerGP\node_modules\aoi.sqlite\classes\Database.js:79:73)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
``` 
once again

**Comment by LightslicerGP** [comment]
```javascript
      let validQuery = typeof query === 'object' ? JSON.stringify(query) : query; // added according to chatgpt 10/10/24
      this.client.db.prepare(sql).run(validQuery);
```

trying this, possibly fixes it (yes i asked chatgpt but like what am i meant to do i dont know enough js or get what is happening)

**Comment by Faf4a** [comment]
should be fixed, reinstall

lmk if you have any other issues
